services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'  # This maps port 27017 on the host to port 27017 in the container

  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'  # Ensure the ports are properly mapped for this service as well
